city_lks = '//div[@class="top-cities"]//a/@href'
city_lks1 = '//span[@class="city-wrapper"]/a/@href'
doc_nodes = '//div[@data-ana="ListingPageView:doctors"]/div[@class="listing-row-wrapper"]'
details_block = './/div[@class="doc-details-block"]'
name_xpath = './/h2[@itemprop="name"]//text()'
qual_ = './/p[@class="doc-qualifications"]/span//text()'
exp_ = './/p[@class="doc-exp-years"]/text()'
specialities_ = './/p[@class="doc-specialties "]//span[@itemprop]//text()'
clinic_name = './/p[@class="doc-clinic-name"]//span[@itemprop="name"]//text()'
url_xpath = './a[@itemprop="url"][@data-doctor-id]/@href'
id_xpath = './a[@itemprop="url"][@data-doctor-id]/@data-doctor-id'
clinic_photos = './/a[img][not(@style)][@data-doctorid]/@href'
doctor_photos_xpath = './/div[@class="doc-photo-container"]//img/@data-originalsrc'
doc_recently_visited_xpath = './/span[@class="doc-last-visited-text"]/text()'
doc_availability_xpath = './/div[@class="doc-availability-block"]'
doc_rating_xpath = './div[contains(@class,"patient_experience_score")]/text()'
doc_votes_xpath = './div[contains(@class,"patient_experience_score")]/span[@class="doctor-votes"]/text()'
doc_loc_latitude_xpath = './/span[@itemprop="geo"]/meta[@itemprop="latitude"]/@content'
doc_loc_longitude_xpath = './/span[@itemprop="geo"]/meta[@itemprop="longitude"]/@content'
doc_feedback_count_xpath = './p[@class="reviews-count"]//text()'
doc_addr_locality_xpath = './p[@itemprop="address"]//span[@itemprop="addressLocality"]/text()'
doc_addr_region_xpath = './p[@itemprop="address"]//span[@itemprop="addressRegion"]/text()'
doc_add_both_xpath = './p[@itemprop="address"]//span[@itemprop]/text()'
doc_fee_amount_xpath = './p[@class="fees"]//span[@class="fees-amount"]/text()'
doc_price_range_xpath = './p[@class="fees"]//meta[@itemprop="priceRange"]/@content'
doc_price_currency_xpath = './p[@class="fees"]//meta[@itemprop="currenciesAccepted"]/@content'
doc_booking_type_xpath = './/span[@class="button-text vn-call-button"]/text()'
doc_schedule_nodes_xpath = './div[@class="timings"]/div[@class="timings-block"]/p'
sch_days_xpath = './span[contains(@class,"strong days-timing")]/text()'
sch_timings_xpath = './span[contains(@class,"hours-timing")]/text()'
next_page_xpath = '//div[@class="paginator"]//a[@class="page_link page_link_next"]/@href'
dct_profile_xpath = '//div[@class="doctor-details-wrapper"]/meta[@itemprop="url"]/@content'
dct_name_xpath = '//div[@class="doctor-details-wrapper"]/h1[@class="doctor-name"]/text()'
dct_qualifications_xpath = '//div[@class="doctor-details-wrapper"]/p[@class="doctor-qualifications"]/text()'
dct_experience_xpath = '//div[@class="doctor-details-wrapper"]/h2[@class="doctor-specialties"]/text()'
dct_photo_xpath = '//div[@class="doc_photo"]//link[@itemprop="photo"]/@href'
dct_specialization_xpath = '//div[@class="doctor-details-wrapper"]/h2[@class="doctor-specialties"]/meta[@itemprop="medicalSpecialty"]/@content'
dct_verification_xpath = '//div[@class="verifications-block"]/span[@class="verification-label"]/text()'
dct_rating_xpath = '//div[@class="doctor-details-wrapper"]//div[contains(@class,"patient_experience_score")]/text()'
dct_votes_xpath = '//div[@class="doctor-details-wrapper"]//span[@class="doctor-votes"]/text()'
dct_summary_xpath = '//div[@class="doctor-summary"]//span[@id="summaryTextFull"]/text()'
dct_services_xpath1 = '//div[@class="services-block"]//div[@class="doc-info-item service-cell "][@itemprop="name"]/a/text()'
dct_services_xpath2 = '//div[@class="services-block"]//div[@class="doc-info-item service-cell "][@itemprop="name"]/text()'
dct_specializations_xpath1 = '//div[@class="doc-info-section specialties-block"]//h2[contains(@class,"doc-info-item specialty")]//a[@itemprop="name"]/text()'
dct_specializations_xpath2 = '//div[@class="doc-info-section specialties-block"]//h2[contains(@class,"doc-info-item specialty")]/text()'
dct_education_xpath = '//div[@class="doc-info-section qualifications-block"]//span[contains(@class,"qualification-degree") or contains(@class,"qualification-details")]/text()'
dct_awards_xpath = '//div[@class="doc-info-section awards-block"]//p[contains(@class,"doc-info-item award")]/text()'
dct_memberships_xpath = '//div[@class="doc-info-section memberships-block"]//p[contains(@class,"doc-info-item membership")]/text()'
dct_organizations_xpath = '//div[@class="doc-info-section organizations-block"]/div[contains(@class,"doc-info-item organization")]'
exp_year_xpath = './span[@class="exp-tenure"]/text()'
exp_details_xpath = './span[@class="exp-details"]/text()'
dct_registrations_xpath = '//div[@class="doc-info-section registrations-block"]//div[contains(@class, "doc-info-item registration")]'
registr_tenure_xpath = './span[@class="exp-tenure"]/text()'
registr_details_xpath = './span[@class="exp-details"]/text()'
feedback_count_xpath = '//a[@id="reviewsNavLink"]/text()'
feedback_count_xpath1 = '//a[@id="all-reviews"]/text()'
doc_id_feedback_xpath = '//input[@type="hidden"][@name="id"][@data-type="doc"]/@value'
hospital_nodes_xpath = '//div[@id="infoTab"]//div[contains(@class,"clinic-block")]'
hsp_location_xpath = './div[@class="clinic-locality"]//text()'
hsp_link_xpath = './/p[@class="map-link-container"]/meta[@itemprop="url"]/@content'
hsp_link_xpath1 = './/div[@class="clinic-address"]/h2/a[@itemprop="name"]/@href'
hsp_name_xpath = './/div[@class="clinic-address"]/h2/a[@itemprop="name"]/text()'
hsp_star_rat_xpath = './/div[@class="practice-star-rating aes-star-rating"]/span[@class="font-star icon-ic_star_solid filled-star"]/@class'
hsp_star_rat1_xpath = './/div[@class="practice-star-rating aes-star-rating"]/span[@class="font-star icon-ic_star_half filled-star"]/@class'
hsp_address_xpath = './/span[@itemprop="streetAddress"]/text()'
hsp_addr_locality_xpath = './/meta[@itemprop="addressLocality"]/@content'
hsp_add_region_xpath = './/meta[@itemprop="addressRegion"]/@content'
hsp_photos_xpath = './/p[@class="clinic-photos-container"]/a[@data-clinicid]/@href'
hsp_booking_type_xpath = './/span[@class="button-text vn-call-button"]/text()'
hsp_map_latitude_xpath = './/p[@class="map-link-container"]//span[@itemprop="geo"]/meta[@itemprop="latitude"]/@content'
hsp_map_longitude_xpath = './/p[@class="map-link-container"]//span[@itemprop="geo"]/meta[@itemprop="longitude"]/@content'
hsp_schedule_xpath = './/div[@class="clinic-timings"]//p[@class="clinic-timings-day"]/text()'
hsp_timesch_xpath = './/div[@class="clinic-timings"]//meta[@itemprop="openingHours"]/@content'
hsp_consultation_fee_xpath = './div[@class="clinic-fees"]/span[@itemprop="priceRange"]/text()'
hsp_fee_indicator_xpath = './div[@class="clinic-fees"]//span[@id="feesindicator"]//div[@class="fees-indicator-tooltip"]//text()'
hsp_currencies_accpe_xpath = './meta[@itemprop="currenciesAccepted"]/@content'
hsp_practo_gura_xpath = './div[@class="clinic-fees"]//div[@class="gc-mini-message"]/a/@href'


