city_lks = '//div[@class="top-cities"]//a/@href'
city_lks1 = '//span[@class="city-wrapper"]/a/@href'
doc_nodes = '//div[@data-ana="ListingPageView:hospital"][@id="resultsContainer"]/div[contains(@class,"listing-row-wrapper ")]'
hsp_star_rat_xpath = './/div[@class="practice-star-rating aes-star-rating"]/span[@class="font-star icon-ic_star_solid filled-star"]/@class'
hsp_star_rat1_xpath = './/div[@class="practice-star-rating aes-star-rating"]/span[@class="font-star icon-ic_star_half filled-star"]/@class'
details_block = './/div[@class="doc-details-block"]'
name_xpath = './/h2[@itemprop="name"]//text()'
qual_ = './/p[@class="doc-qualifications"]/span//text()'
exp_ = './/p[@class="doc-exp-years"]/text()'
#specialities_ = './/p[@class="doc-specialties "]//span[@itemprop]//text()'
specialities_ = './/p[@class="doc-specialties"]//span[@itemprop="medicalSpecialty"]/span/a/text()'
clinic_name = './/p[@class="doc-clinic-name"]//span[@itemprop="name"]//text()'
#url_xpath = './a[@class="link doc-name"]/@href'
url_xpath = './/meta[@itemprop="url"]/@content'
doctor_photos_xpath = './/div[@class="doc-photo-container"]//img/@data-originalsrc'
doc_recently_visited_xpath = './/span[@class="doc-last-visited-text"]/text()'
doc_availability_xpath = './/div[@class="doc-availability-block"]'
doc_rating_xpath = './div[contains(@class,"patient_experience_score")]/text()'
doc_votes_xpath = './div[contains(@class,"patient_experience_score")]/span[@class="doctor-votes"]/text()'
doc_feedback_count_xpath = './p[@class="reviews-count"]//text()'
doc_fee_amount_xpath = './p[@class="fees"]//span/text()'
doc_booking_type_xpath = './/span[@class="button-text vn-call-button"]/text()'
#doc_booking_type_xpath = './/*[contains(@class,"button-text")]/text()'
"""doc_schedule_nodes_xpath = './div[@class="timings"]/div[@class="timings-wrapper"]/p'
sch_days_xpath = './span[contains(@class,"strong days-timing")]/text()'
sch_timings_xpath = './span[contains(@class,"hours-timing")]/text()'"""
schedule_timings =  './/meta[@itemprop="openingHours"]/@content'
practo_guarentee=  './/a[@href="http://prac.to/guarantee"]//span/text()'
doc_price_currency_xpath = './p[@class="fees"]//meta[@itemprop="currenciesAccepted"]/@content'
feedback_count_xpath = '//a[@id="reviewsNavLink"]/text()'
feedback_count_xpath1 = '//a[@id="all-reviews"]/text()'
doc_id_feedback_xpath = '//input[@type="hidden"][@name="id"][@data-type="prac"]/@value'

hosp_link_xpb = './/div[contains(@class,"hospital-name-container")]/a[@itemprop="url"]/@href'
hosp_id_xpb = './/div[contains(@class,"hospital-name-container")]/a[@itemprop="url"]/@data-ana'
hosp_name_xpb = './/div[contains(@class,"hospital-name-container")]//h2[@itemprop="name"]/text()'
hosp_location_xpb = './/div[contains(@class,"hospital-name-container")]//span[@itemprop="addressLocality"]/text()'
hosp_medical_speciality_xpb = './/div[contains(@class,"hospital-name-container")]//span[@itemprop="medicalSpecialty"]/text()'
hosp_no_of_doctor_xpb = './/div[contains(@class,"hospital-name-container")]//div[@class="estab-row clinic-elements"]//div[@class="estab-doctors-specialties"]/parent::div/p/text()'
hospital_images_xpb = './/div[contains(@class, "clinic-photo-container")]/a/@href'
hosp_feedback_count_xpb = './/div[@class="estab-reviews-count"]/parent::div/p/a/text()'
hosp_open_h_xpb = './/p[@class="always-open"]/text()'
hosp_practo_guarentee_xpb = './/a[@href="http://prac.to/guarantee"]//img/@src'
doc_booking_type_xpb = './/*[contains(@class,"button-text")]/text()'
doc_schedule_nodes_xpb = './/div[@class="estab-timings"]/parent::div/div[@class="estab-col"]/p'
sch_days_xpb = './span[contains(@class,"strong days-timing")]/text()'
sch_timings_xpb = './span[contains(@class,"hours-timing")]/text()'
hosp_iso_accr_xpb = './/div[contains(@class,"hospital-name-container")]//div[@class="estab-row clinic-elements clinic-speciality-spacing"]/div[@class="estab-doctors-specialties"]/parent::div/p/text()'
next_path_xpb = '//div[@class="paginator"]//a[@class="page_link page_link_next"]/@href'
hosp_photo_xpt = '//div[@class="practice-logo"]/img[@itemprop="logo"]/@src'
hosp_name_xpt = '//div[@class="profile-summary"]/h1/text()'
hosp_pf_link_xpt = '//div[@class="profile-summary"]/meta[@itemprop="url"]/@content'
rating_values_xpt = '//div[@itemprop="aggregateRating"]/meta[@itemprop="ratingValue"]/@content'
rating_count_xpt = '//div[@itemprop="aggregateRating"]/meta[@itemprop="ratingCount"]/@content'
clinic_location_xpt = '//h2[@class="clinic-location"]/text()'
medical_spec_xpt = '//h2[@itemprop="medicalSpecialty"]/text()'
number_of_doctors_xpt = '//div[@class="profile-summary"]/h2[not(@*)]/text()[contains(.,"Doctor")]'
hospt_description_xpt = '//p[@itemprop="description "]/span[@id="summaryTextFull"]/text()'
no_of_beds_xpt = '//span[@class="bold-font"][contains(text(),"No. of Beds")]/parent::div/span[not(@*)]/text()'
no_of_ambulances_xpt = '//span[@class="bold-font"][contains(text(),"No. of Ambulances")]/parent::div/span[not(@*)]/text()'
method_of_payment_xpt = '//span[@class="payment-data"]/text()'
hospital_address_xpt = '//div[@class="hospital-address"]/p/text()'
street_address_xpt = '//span[@itemprop="address"]/meta[@itemprop="streetAddress"]/@content'
address_locality_xpt = '//span[@itemprop="address"]/meta[@itemprop="addressLocality"]/@content'
address_region_xpt = '//span[@itemprop="address"]/meta[@itemprop="addressRegion"]/@content'
postal_code_xpt = '//span[@itemprop="address"]/meta[@itemprop="postalCode"]/@content'
opening_timings_xpt = '//div[@class="overview-timings"]/p[@class="timings-always-open"]/text()'
doc_schedule_nodes_xpt = '//div[@class="overview-timings"]/p[@class="overview-timings-day-label"]'
sch_days_xpt = './self::p/text()'
sch_timings_xpt = './following-sibling::p[1]/text()'
hospital_images_xpt = '//div[@class="slideshow-screen"]//link[@itemprop="photo"]/@href'
amenities_xpt = '//div[contains(@class,"overview-amenities")]//span[@class="amenity-name"]/text()'
amenities_xpt1 = '//div[contains(@class,"overview-amenities")]//span[@class="amenity-name"]/a/text()'
emergency_contact_number_xpt = '//span[@class="emergency-contact"]/text()'
services_xpt = '//div[@class="service-cell"][@itemprop="name"][not(a)]/text()'
services_xpt1 = '//div[@class="service-cell"][@itemprop="name"]/a/text()'
latitude_xpt = '//div[@itemprop="geo"]/meta[@itemprop="latitude"]/@content'
longitude_xpt = '//div[@itemprop="geo"]/meta[@itemprop="longitude"]/@content'
branch_setup_xpt = '//div[@class="overviewTab overview-block tabs"]/text()'
branch_setup_xpt1 = '//div[@class="overviewTab overview-block tabs"]//span[@class="establishment-data"]/text()'
doctor_nodes_xpt = '//div[@class="doctor-tab-container doctorsTab"]//div[@itemprop="member"]'
nex_pge_doc_xpt = '//div[@class="doctor-tab-container doctorsTab"]/div[@class="paginator"]//a[@class="page_link page_link_next"]/text()'
awards_xpt = '//span[@class="seg-services-title"][contains(text(),"Awards")]/parent::div/following-sibling::div/span/text()'
other_centers_title_xpt = '//div[@itemtype="https://schema.org/MedicalClinic"]//a[@itemprop="url"]'
ocen_id_xpt = './self::a/@data-practice-id'
ocen_name_xpt = './h2[@itemprop="name"]/text()'
doctor_nodes_xptd = '//div[@itemprop="member"][contains(@class, "doctorsTab")]'
next_page_doc_xptd = '//div[@class="paginator"]//a[@class="page_link page_link_next"]/@data-page'
doc_id_xpts = './/input[@type="checkbox"]/@data-doctorid'
doc_practo_gua_xpts = './/a[@href="http://prac.to/guarantee"]//span/text()'
doc_on_call_xpts = './/div[@id="onCall"]/span[@class="on-call-doctor"]/text()'
