pi_crawl  = """ CREATE TABLE `pi_crawl` (
  `sk` varchar(75) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `profiles_start_modified_at` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `profiles_end_modified_at` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `profiles_sheet_status` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `profiles_run_status` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`profiles_start_modified_at`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"""

twitter_meta = """ CREATE TABLE `Twitter_latest` (
  `sk` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `screen_name` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci,
  `location` varchar(300) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `tweets` int(11) DEFAULT '0',
  `following` int(11) DEFAULT '0',
  `followers` int(11) DEFAULT '0',
  `likes` int(11) DEFAULT '0',
  `image` text COLLATE utf8_unicode_ci,
  `lists` text COLLATE utf8_unicode_ci,
  `timezone` varchar(10) COLLATE utf8_unicode_ci DEFAULT '',
  `language` text COLLATE utf8_unicode_ci,
  `is_verified` int(11) DEFAULT '0',
  `twitter_url` text COLLATE utf8_unicode_ci,
  `email_id` text COLLATE utf8_unicode_ci,
  `aux_info` text COLLATE utf8_unicode_ci,
  `top_10_hashtags` text COLLATE utf8_unicode_ci,
  `top_5_mentioned_users` text COLLATE utf8_unicode_ci,
  `retweeted_percentage` text COLLATE utf8_unicode_ci,
  `retweeted_users` text COLLATE utf8_unicode_ci,
  `Most_referenced_domains` text COLLATE utf8_unicode_ci,
  `detected_sources` text COLLATE utf8_unicode_ci,
  `detected_languages` text COLLATE utf8_unicode_ci,
  `Avg_no_of_tweets_per_day` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

twitter_crawl = """CREATE TABLE `twitter_crawl` (
  `sk` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `url` text COLLATE utf8_unicode_ci,
  `crawl_type` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `content_type` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `related_type` varchar(50) COLLATE utf8_unicode_ci DEFAULT '',
  `crawl_status` int(3) NOT NULL DEFAULT '0',
  `meta_data` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sk`,`content_type`,`crawl_status`),
  KEY `sk` (`sk`),
  KEY `type` (`crawl_type`),
  KEY `type_time` (`crawl_type`,`modified_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"""

facebook_crawl = """CREATE TABLE `facebook_crawl` (
  `sk` varchar(300) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `url` text COLLATE utf8_unicode_ci,
  `crawl_type` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `content_type` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `related_type` varchar(50) COLLATE utf8_unicode_ci DEFAULT '',
  `crawl_status` int(3) NOT NULL DEFAULT '0',
  `meta_data` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sk`,`content_type`,`crawl_status`),
  KEY `sk` (`sk`),
  KEY `type` (`crawl_type`),
  KEY `type_time` (`crawl_type`,`modified_at`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci """

facebook_meta = """ CREATE TABLE `facebook_profiles` (
  `sk` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `name` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `profile_id` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `aux_info` text COLLATE utf8_unicode_ci,
  `aux_info_read_followers` text COLLATE utf8_unicode_ci,
  `aux_info_books_likes` text COLLATE utf8_unicode_ci,
  `aux_info_read_books` text COLLATE utf8_unicode_ci,
  `aux_info_movie_watched` text COLLATE utf8_unicode_ci,
  `aux_info_movie_likes` text COLLATE utf8_unicode_ci,
  `aux_info_tvshow_watched` text COLLATE utf8_unicode_ci,
  `aux_info_tvshow_likes` text COLLATE utf8_unicode_ci,
  `aux_info_inspirational_people` text COLLATE utf8_unicode_ci,
  `aux_info_sports` text COLLATE utf8_unicode_ci,
  `aux_info_family` text COLLATE utf8_unicode_ci,
  `aux_info_education` text COLLATE utf8_unicode_ci,
  `aux_info_work` text COLLATE utf8_unicode_ci,
  `aux_info_clothing` text COLLATE utf8_unicode_ci,
  `aux_info_friends` text COLLATE utf8_unicode_ci,
  `aux_info_atheletes` text COLLATE utf8_unicode_ci,
  `aux_info_teams` text COLLATE utf8_unicode_ci,
  `aux_info_book` text COLLATE utf8_unicode_ci,
  `aux_info_music` text COLLATE utf8_unicode_ci,
  `aux_info_games` text COLLATE utf8_unicode_ci,
  `aux_info_websites` text COLLATE utf8_unicode_ci,
  `aux_info_restaurants` text COLLATE utf8_unicode_ci,
  `aux_info_activities` text COLLATE utf8_unicode_ci,
  `aux_info_interests` text COLLATE utf8_unicode_ci,
  `aux_info_tvshows` text COLLATE utf8_unicode_ci,
  `aux_info_movies` text COLLATE utf8_unicode_ci,
  `aux_info_others` longtext COLLATE utf8_unicode_ci,
  `profile_url` text COLLATE utf8_unicode_ci,
  `created_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`sk`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci"""

FB_TW_TABLES = {"twitter_meta" : twitter_meta,
                "twitter_crawl" : twitter_crawl,
                "facebook_crawl" : facebook_crawl,
                "facebook_meta" : facebook_meta,
  		"pi_crawl" : pi_crawl}
