# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

from scrapy.item import Item, Field

class Fbpagesmeta(Item):
	 page_sk     = Field()
	 page_url    = Field()
	 page_id     = Field()
	 page_name   = Field()

class Fbpagespost(Item):
	page_sk			= Field()
	page_id			= Field()
	post_sk			= Field()
	post_id			= Field()
	post_shares_count	= Field()
	post_url		= Field()
	post_message		= Field()
	post_created_time	= Field()
	post_updated_time	= Field()
	post_picture		= Field()
	post_from_name		= Field()
	post_from_id		= Field()
	post_to_name		= Field()
	post_to_id		= Field()
	post_comments_total_count	= Field()
	post_reactions_total_count	= Field()
	post_like_count		= Field()
	post_love_count		= Field()
	post_wow_count		= Field()
	post_haha_count 	= Field()
	post_sad_count		= Field()
	post_angry_count	= Field()
	post_json_url		= Field()
class Fbpagespostcomment(Item):
	page_sk				= Field()
	page_id				= Field()
	post_sk				= Field()
	post_id				= Field()
	comment_sk			= Field()
	comment_id			= Field()
	comment_from_id			= Field()
	comment_from_name		= Field()
	comment_message			= Field()
	comment_created_time		= Field()
	inner_comments_total_count	= Field()
	comment_reactions_total_count = Field()
	comment_like_count	= Field()
	comment_love_count	= Field()
	comment_wow_count	= Field()
	comment_haha_count	= Field()
	comment_sad_count	= Field()
	comment_angry_count	= Field()

class Fbpagespostinnercomment(Item):
	page_sk				= Field()
	page_id				= Field()
	post_sk				= Field()
	post_id				= Field()
	comment_sk			= Field()
	comment_id			= Field()
	inner_comment_sk		= Field()
	inner_comment_id		= Field()
	inner_comment_from_id		= Field()
	inner_comment_from_name		= Field()
	inner_comment_message		= Field()
	inner_comment_created_time	= Field()
	innercomment_like_count		= Field()
	inner_comment_love_count	= Field()
	inner_comment_wow_count		= Field()
	inner_comment_haha_count	= Field()
	inner_comment_sad_count		= Field()
	inner_comment_angry_count	= Field()
	inner_comment_reactions_total_count = Field()

class Fbpagespostreactions(Item):
	reaction_sk	= Field()
	page_sk		= Field()
	page_id		= Field()
	post_sk		= Field()
	post_id		= Field()
	member_id	= Field()
	member_name	= Field()
	reaction_type	= Field()
class Fbpagepostcommentreac(Item):
        reaction_sk     = Field()
        page_sk         = Field()
        page_id         = Field()
        post_sk         = Field()
        post_id         = Field()
	comment_sk	= Field()
	comment_id	= Field()
        member_id       = Field()
        member_name     = Field()
        reaction_type   = Field()
class Fbpagepostinnercommnetreac(Item):
        reaction_sk     = Field()
        page_sk         = Field()
        page_id         = Field()
        post_sk         = Field()
        post_id         = Field()
        comment_sk      = Field()
        comment_id      = Field()
	inner_comment_sk= Field()
	inner_comment_id= Field()
        member_id       = Field()
        member_name     = Field()
        reaction_type   = Field()
