list_tables = ['linkedin_certifications', 'linkedin_courses', 'linkedin_following_channels', 'linkedin_following_companies', 'linkedin_following_influencers', 'linkedin_following_schools', 'linkedin_given_recommendations', 'linkedin_groups', 'linkedin_organizations', 'linkedin_posts', 'linkedin_projects', 'linkedin_received_recommendations', 'linkedin_skills', 'linkedin_volunteer_experiences', 'linkedin_publications', 'linkedin_testscore']
list_tables1 = ['linkedin_educations', 'linkedin_experiences', 'linkedin_honors']
crawl_table_query = "select sk, url, meta_data, crawl_status from linkedin_crawl where date(created_at) >= '%s' limit %s"
sheet_name = 'linkedin_enrichment_profiles_%s_%s.csv'
member_id_track = 'select member_id from linkedin_track where sk = "%s"'
header_params_list = ['original_url', 'id', 'status of url', 'Data Available/UnAvailable', 'email_id', 'key', 'profile_url', u'profileview_url', u'name', u'first_name', u'last_name', u'member_id', u'headline', u'no_of_followers', u'profile_post_url', u'summary', u'number_of_connections', u'industry', u'location', u'languages', u'emails', u'websites', u'addresses', u'message_handles', u'phone_numbers', u'birthday', u'birth_year', u'birth_month', u'twitter_accounts', u'profile_image', u'interests', u'location_postal_code', u'location_country_code', u'background_image', u'image_path']
header_params_list = header_params_list + list_tables
q8_metadesign = 'select * from %s where sk ="%s" and date(last_seen)>= "%s"'
q1_querydesign = 'select * from %s where profile_sk="%s" and date(last_seen)>= "%s"'
q6_column_maxcount = "select count(*)  from %s where date(last_seen)>= '%s' group by profile_sk order by count(*) desc limit 1"
dict_of_fields = {"linkedin_certifications":['certification_id', 'certification_date', 'certification_title', 'certification_company_logo', 'certification_company_name', 'certification_license'], "linkedin_courses":['course_name', 'course_number'], "linkedin_following_channels":['channel_followers', 'channel_title', 'channel_link', 'channel_image'], "linkedin_following_influencers":['inflencer_name', 'influencer_firstname', 'influencer_lastname', 'influencer_image', 'influencer_profile_url', 'influencer_headline', 'influencer_followers_count'], "linkedin_following_schools":['school_name', 'school_image', 'school_region', 'school_link', 'total_followee_count'], "linkedin_given_recommendations":['last_name', 'name', 'date_and_relationship', 'title', 'created_date', 'summary', 'profile_image', 'profile_member_id', 'profile_url', 'recommendation_id'], "linkedin_groups":['group_link', 'group_name', 'no_of_members', 'group_logo', 'group_id', 'group_description'], "linkedin_organizations":['name', 'position', 'start_date', 'end_date', 'description', 'occupation_name'], "linkedin_posts":['post_url', 'post_image', 'post_title', 'post_author_id', 'post_state', 'post_date', 'post_article_id'], "linkedin_projects":['project_date', 'number_of_project_members', 'project_member_names', 'project_occupation_name', 'project_title', 'project_url', 'project_start_date', 'project_end_date', 'project_description'], "linkedin_received_recommendations":['role', 'profile_member_id', 'id', 'edu_start_date', 'name', 'organization', 'created_date', 'date_and_relationship', 'headline', 'profile_url', 'profile_image', 'summary'], "linkedin_skills":['skill_name', 'endoresement_count', 'member_topic_skill_url', 'public_topic_skill_url'], "linkedin_volunteer_experiences":['volunteer_interests', 'volunteer_role', 'volunteer_cause', 'organization_name', 'organization_logo', 'description', 'start_date_year', 'start_date_month', 'volunteer_date', 'end_date_year', 'end_date_month', 'organization_id'], "linkedin_publications":['publication_title', 'publication_url', 'publisher', 'publication_description', 'publication_date'], "linkedin_testscore":['testscore_name', 'testscore_description', 'testscore', 'testscore_day', 'testscore_month', 'testscore_year'], "linkedin_following_companies":['company_canonical_name', 'total_followee_count', 'company_logo', 'company_universal_name', 'company_url'], "linkedin_educations":['edu_start_year', 'edu_start_month', 'edu_start_date', 'edu_end_year', 'edu_end_date', 'edu_end_month', 'edu_degree', 'edu_field_of_study', 'edu_school_name', 'school_logo', 'edu_grade', 'edu_activities', 'post_article_id', 'education_id', 'school_id'], "linkedin_experiences":['exp_location', 'exp_company_name', 'exp_company_url', 'exp_title', 'start_date', 'end_date', 'exp_company_logo', 'exp_duration', 'exp_company_id', 'exp_position_id', 'exp_summary'], "linkedin_honors":['honor_on', 'honor_issuer', 'honor_summary', 'honor_title', 'occupation']}
