qu1 = "select sk, profile_image from linkedin_meta where member_id = '%s'"
qu2 = "update linkedin_meta set image_path = '%s' where sk = '%s' and member_id = '%s'"
#qu3 = "update linkedin_meta set image_path = '%s' where member_id = '%s'"
qu4  = "select sk, member_id, profile_image, image_path, profile_url  from linkedin_meta where image_path != '';"
qu5 = "select count(*), member_id, image_url, image_path from linkedin_connections where image_url != '' group by member_id having count(*)>=1"
qu6 = "select sk, member_id from linkedin_meta where member_id = '%s'"
qu7 = "update linkedin_meta set profile_image= '%s', image_path = '%s' where member_id = '%s'"
qu8 = "select member_id, image_url, image_path from linkedin_connections where image_url != '' and member_id= '%s' order by member_id desc limit 1"
qu9 = "select sk, member_id, profile_image, image_path, profile_url  from linkedin_meta where image_path is NULL and profile_image != '';"
qu10 = "select sk, member_id, profile_image, image_path, profile_url  from linkedin_meta where image_path is not NULL and profile_image = '';"
qu11 = "select profile_image from linkedin_meta where image_path is not NULL and profile_image != '' and member_id = '%s'"
qu12 = "update linkedin_meta set profile_image = '%s' where sk = '%s' and member_id = '%s'"
qu13 = "select distinct member_id from linkedin_meta where profile_url like '%authToken%' or profile_url like '%view?id=%'"
qu14 = "select profile_url from linkedin_connectionprofiles where member_id = '%s'"
qu15 = "update  linkedin_meta set profile_url='%s' where member_id = '%s'"
qu16 = "select sk, profile_image, profile_url from linkedin_meta where member_id = '%s'"
#qu17 = "select sk, profile_image, profile_url, member_id from linkedin_meta where profile_image = '' order by rand() limit %s" %(self.limit)
qu17 = "select sk, profile_image, profile_url, member_id from linkedin_meta where profile_image != '' and image_path = ''"
qu18  = "select member_id from linkedin_connectionprofiles where image_path is NULL" 
qu19 = "select profile_image, image_path from linkedin_meta where member_id = '%s' limit 1"
qu20 = "update linkedin_connectionprofiles set profile_image = '%s', image_path='%s' where member_id='%s' and image_path is NULL"
qu21 = "update linkedin_connectionprofiles set profile_image = '%s', image_path='%s' where member_id='%s'"
qu22 = "update linkedin_connectionprofiles set image_path = '%s' where member_id = '%s'"
image_full_path = "/root/Linkedin/Linkedin/spiders/images/full/"
pulse_url = 'https://www.linkedin.com/pulse-fe/api/v1/followableEntity?vanityName=%s'
#developer_pf_url = "%s%s%s"%('https://www.linkedin.com/cws/member/public_profile?public_profile_url=', profile_url, "&ffalse&original_referer=https%3A%2F%2Fdeveloper.linkedin.com%2Fetc%2Fdesigns%2Flinkedin%2Fkaty%2Fglobal%2Fclientlibs%2Fhtml%2Fsands%3Dmiddle-center&token=&isFramed=true&lang=en_US&_ts=1490264453590.3835&xd_origin_host=https%3A%2F%2Fdeveloper.linkedin.com")
