# -*- coding: utf-8 -*-

from scrapy.item import Item, Field
class JuicerItem(Item):
    pass
class BestSellers(Item):
    product_id                  = Field()
    name                        = Field()
    no_of_reviews               = Field()
    star_rating                 = Field()
    price                       = Field()
    rank                        = Field()
    week_number                 = Field()
    category                    = Field()
    is_prime                    = Field()
    product_url                 = Field()
    reference_url               = Field()
class Products(Item):
    id                          = Field()
    name                        = Field()
    original_price              = Field()
    discount_price              = Field()
    features                    = Field()
    description                 = Field()
    item_number                 = Field()
    date_available              = Field()
    best_sellerrank             = Field()
    aux_info                    = Field()
    reference_url               = Field()
class RelatedSellers(Item):
    related_sk                  = Field()
    product_id                  = Field()
    name                        = Field()
    category                    = Field()
    product_condition           = Field()
    seller_name                 = Field()
    seller_no_of_rating         = Field()
    seller_rating_percentage    = Field()
    seller_price                = Field()
    is_prime                    = Field()
    aux_info                    = Field()
class RichMedia(Item):
    sk                          = Field()
    product_id                  = Field()
    category                    = Field()
    size                        = Field()
    dimensions                  = Field()
    image_url                   = Field()
    reference_url               = Field()
    aux_info                    = Field()
class CustomerReviews(Item):
    sk                          = Field()
    product_id                  = Field()
    name                        = Field()
    reviewed_by                 = Field()
    reviewed_on                 = Field()
    review                      = Field()
    category                    = Field()
    review_url                  = Field()
    review_rating               = Field()
    verified_purchase_flag      = Field()
    aux_info                    = Field()
class Twitter(Item):
    sk                          = Field()
    screen_name                 = Field()
    name                        = Field()
    description                 = Field()
    location                    = Field()
    tweets                      = Field()
    following                   = Field()
    followers                   = Field()
    likes                       = Field()
    image                       = Field()
    lists                       = Field()
    timezone                    = Field()
    language                    = Field()
    is_verified                 = Field()
    twitter_url                 = Field()
    email_id                    = Field()
    aux_info                    = Field()
class Linkedin(Item):
    sk                          = Field()
    name                        = Field()
    first_name                  = Field()
    last_name                   = Field()
    locality                    = Field()
    image                       = Field()
    member_url                  = Field()
    mark                        = Field()
    url                         = Field()
class Linkedinpostions(Item):
    sk                          = Field()
    profile_sk                  = Field()
    title                       = Field()
    organization                = Field()
class Linkedinviewers(Item):
    sk                          = Field()
    profile_sk                  = Field()
    viewer_url                  = Field()
    viewer_name                 = Field()
    viewer_headline             = Field()
class Comments(Item):
    sk                          = Field()
    review_sk                   = Field()
    comment_name                = Field()
    comment_by                  = Field()
    comment_on                  = Field()
    comment                     = Field()
    comment_votes               = Field()
    aux_info                    = Field()
class DoctorInfo(Item):
    doctor_id                   = Field()
    doctor_name                 = Field()
    doctor_profile_link         = Field()
    qualification               = Field()
    years_of_experience         = Field()
    specialization              = Field()
    recently_visited_for        = Field()
    rating                      = Field()
    vote_count                  = Field()
    feedback_count              = Field()
    location                    = Field()
    address                     = Field()
    consultation_fee            = Field()
    schedule_timeslot           = Field()
    doctor_image                = Field()
    clinic_names                = Field()
    clinic_images               = Field()
    location_latitude           = Field()
    location_longitude          = Field()
    region                      = Field()
    fee_currency                = Field()
    booking_type                = Field()
    reference_url               = Field()
    aux_info                    = Field()
class DoctorMeta(Item):
    sk                          = Field()
    doctor_id                   = Field()
    doctor_name                 = Field()
    doctor_profile_link         = Field()
    qualification               = Field()
    specialization              = Field()
    years_of_experience         = Field()
    medical_registration_verified= Field()
    rating                      = Field()
    vote_count                  = Field()
    summary                     = Field()
    latitude                    = Field()
    longitude                   = Field()
    services                    = Field()
    specializations             = Field()
    awards_recognitions         = Field()
    education                   = Field()
    memeberships                = Field()
    experience                  = Field()
    registrations               = Field()
    feedback_count              = Field()
    doctor_image                = Field()
    reference_url               = Field()
    aux_info                    = Field()

class DoctorFeedback(Item):
    sk                          = Field()
    doctor_id                   = Field()
    feedback_count              = Field()
    feedback_filters             = Field()
    feedback_name               = Field()
    feedback_like               = Field()
    feedback_publish_date       = Field()
    feeback_text                = Field()
    feedback_helpful_count      = Field()
    feedback_helpful_overallcount=Field()
    feedback_reply              = Field()
    feedback_practice_name      = Field()
    feedback_practice_locality  = Field()
    feedback_practice_city      = Field()
    feedback_for                = Field()
    reference_url               = Field()
    aux_info                    = Field()

class DoctorHospital(Item):
    sk                          = Field()
    doctor_id                   = Field()
    hospital_location           = Field()
    hospital_link               = Field()
    hospital_name               = Field()
    hospital_rating             = Field()
    hospital_address            = Field()
    hospital_monday_timing      = Field()
    hospital_tuesday_timing     = Field()
    hospital_wednesday_timing   = Field()
    hospital_thursday_timing    = Field()
    hospital_friday_timing      = Field()
    hospital_saturday_timing    = Field()
    hospital_sunday_timing      = Field()
    hospital_consultation_fee   = Field()
    hospital_practo_gurantee    = Field()
    hospital_photos             = Field()
    hospital_booking_type       = Field()
    hospital_latitude           = Field()
    hospital_longitude          = Field()
    reference_url               = Field()
    aux_info                    = Field()



