mainpage_metaquery = "insert into Maharera_mainpage(sk,promoter_name,last_modified_at,view_link,extention_certificate,reference_url,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

mahameta_query = "insert into MahaRera_Meta(sk , information_type,organization_name,organization_type,description_for_other_organization,organization_past_experience,organization_address_block_number,organization_address_building_name,organization_address_street_name,organization_address_locality,organization_address_landmark,organization_address_state,organization_address_division,organization_address_district,organization_address_taluka,organization_address_village,organization_address_pincode,organization_contact_office_number,organization_contact_website_url ,fsi_built_area_proposed,fsi_built_area_approved,fsi_totalfsi,uploaded_documents,reference_url,aux_info,created_at, modified_at)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

projectmaha_metaquery = "insert into MahaRera_ProjectMeta(sk,program_sk,project_name ,project_status ,proposed_date_of_completion,revised_proposed_date_of_completion,litications_related_project,project_type,project_any_promoter,project_plot_surveynumber,project_boundaries_east ,project_boundaries_west ,project_boundaries_north ,project_boundaries_south ,project_state ,project_division ,project_district ,project_taluka ,project_village,project_street ,project_locality,project_pincode ,project_area ,project_total_buildings ,project_sanctioned_buildings ,project_proposed_but_not_sanctioned,project_aggregate_area_recreational_open_space,reference_url ,aux_info,created_at, modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

past_exp_metaquery = "insert into past_experience_details(sk,program_sk,project_name,type_of_project,others,land_area_in_sq_mtr,address,cts_number,no_of_buildings_plot,no_of_appartments,original_proposed_date_of_completion,actual_date_of_completion,reference_url,aux_info,created_at, modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

member_info_metaquery = "insert into member_information(sk,program_sk,member_name,designation,reference_url,aux_info,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

pro_det_metaquery = "insert into project_details(sk,program_sk,name,proposed,booked,work_done,reference_url,aux_info,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

dev_work_metaquery = "insert into development_work(sk,program_sk,common_area_facilities,available,percent,details,reference_url,aux_info,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

proj_prof_metaquery = "insert into project_prof_information(sk,program_sk,professional_name,certificate_no,prof_type,reference_url,aux_info,created_at, modified_at) values(%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

litigation_det_metaquery = "insert into litigation_details(sk,program_sk,litigation_project_name,litigation_court_name,litigation_case_number,litigation_case_type,litigation_pre_inj_interim_passed,litigation_petition_name,litigation_other_petition_details,litigation_year,litigation_present_status,litigation_documents,reference_url,aux_info,created_at, modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

build_det_apartment_metaquery = "insert into building_details_apartment_type(sk,program_sk,project_name,name,proposed_date,no_of_basements,no_of_plinth,no_of_podium,no_of_slab,no_of_stilts,no_of_open_parking,no_of_closed_parking,apartment_type,carpet_area_in_sqmts,no_of_apartments,no_of_booked_apartment,reference_url,aux_info,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

build_det_tasks_metaquery = "insert into building_details_tasks(sk,program_sk,project_name,name,proposed_date,no_of_basements,no_of_plinth,no_of_podium,no_of_slab,no_of_stilts,no_of_open_parking,no_of_closed_parking,tasks_activity,percentage_of_work,reference_url,aux_info,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

compliant_metaquery = "insert into compliant_details(sk,program_sk,complaint_no,complaint_name,reference_url,created_at,modified_at) values(%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at = now()"

promoter_det_metaquery = "insert into promoter_details(sk,program_sk, project_name, promoter_name, promoter_type,type_of_aggrement,office_number,other_details,reference_url,created_at,modified_at) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now()) on duplicate key update modified_at=now()" 
